### ISSUE TITLE
cant get it to work

### ISSUE THREAD

**Issue by krussedull** [peterhanania/reaction-roles#1]
Error: Cannot find module 'moment-duration-format'
Require stack:
- C:\Reactbot\events\message\message.js
- C:\Reactbot\structures\Util.js
- C:\Reactbot\bot.js
- C:\Reactbot\index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (C:\Reactbot\events\message\message.js:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Util.loadEvents (C:\Reactbot\structures\Util.js:82:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Reactbot\\events\\message\\message.js',
    'C:\\Reactbot\\structures\\Util.js',
    'C:\\Reactbot\\bot.js',
    'C:\\Reactbot\\index.js'
  ]
}

**Comment by peterhanania** [comment]
You can easily fix this issue by writing `npm i moment-duration-format`. Let me know if it works!

**Comment by krussedull** [comment]
Worked well!!:D

Få Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by peterhanania** [comment]
👍
