### ISSUE TITLE
Mongodb url

### ISSUE THREAD

**Issue by Pinokio42** [peterhanania/reaction-roles#5]
LOADED BOT!
(node:4520) UnhandledPromiseRejectionWarning: Error: Cannot find module 'moment-duration-format'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
at Object.<anonymous> (/app/events/message/message.js:10:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
at Util.loadEvents (/app/structures/Util.js:82:17)
(node:4520) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4520) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:4520) UnhandledPromiseRejectionWarning: MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://docs.atlas.mongodb.com/security-whitelist/
    at NativeConnection.Connection.openUri (/rbd/pnpm-volume/87c8fa52-0634-4d1e-acc6-6bddb8388563/node_modules/.registry.npmjs.org/mongoose/5.13.9/node_modules/mongoose/lib/connection.js:846:32)
    at _mongoose._promiseOrCallback.cb (/rbd/pnpm-volume/87c8fa52-0634-4d1e-acc6-6bddb8388563/node_modules/.registry.npmjs.org/mongoose/5.13.9/node_modules/mongoose/lib/index.js:351:10)
    at Promise (/rbd/pnpm-volume/87c8fa52-0634-4d1e-acc6-6bddb8388563/node_modules/.registry.npmjs.org/mongoose/5.13.9/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5)
    at new Promise (<anonymous>)
    at promiseOrCallback (/rbd/pnpm-volume/87c8fa52-0634-4d1e-acc6-6bddb8388563/node_modules/.registry.npmjs.org/mongoose/5.13.9/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (/rbd/pnpm-volume/87c8fa52-0634-4d1e-acc6-6bddb8388563/node_modules/.registry.npmjs.org/mongoose/5.13.9/node_modules/mongoose/lib/index.js:1149:10)
    at Mongoose.connect (/rbd/pnpm-volume/87c8fa52-0634-4d1e-acc6-6bddb8388563/node_modules/.registry.npmjs.org/mongoose/5.13.9/node_modules/mongoose/lib/index.js:350:20)
at botClient.start (/app/bot.js:67:14)
at Object.<anonymous> (/app/index.js:17:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
(node:4520) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by peterhanania** [comment]
`npm install moment-duration-format`
